# Generated by Django 5.1.4 on 2025-09-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='token',
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='code',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
